jwt.token.validity=180000000000
jwt.signing.key=signingkey
jwt.authorities.key=roles
jwt.token.prefix=Bearer
jwt.header.string=Authorization


##Prod Credentials

razorpay.url=https://api.razorpay.com
razorpay.razorPayKey=rzp_live_kDeQiiugysVZ7B
razorpay.razorPayAuth=0qGbJK6yot8r9vRpHiNNTZfT



####Axis Bank Power API 
axispowerapi.encvalue=CCBE9778CC9045047DAC3C35926C1A8F
axispowerapi.X-IBM-Client-Id=f1d0bc3a-4bfa-43f1-a30b-492b27cf557e
axispowerapi.X-IBM-Client-Secret=hN8iI6tO3eU2gG0hW8lD5pF7rF6yE5dV6pG8eV0pN5fT0fT2wC
axispowerapi.url=https://saksham.axisbank.co.in/gateway/api/txb/v1/payments/transfer-payment
spring.jpa.properties.hibernate.jdbc.batch_size=500


##TEST Credentials
#axispowerapi.X-IBM-Client-Id=4b7bc5d3-fa9b-4784-ad69-98c195069979
#axispowerapi.X-IBM-Client-Secret=D3pY2oG1sJ3fA3yH6iS7uV8sH2mG8lX7wM8qJ5kV3xT3xQ5qF4


##razorpay.razorPayKey=rzp_test_GSWPMCWmuwtiQd4
##�razorpay.razorPayAuth =BvMVoRteRFtydBXWYqvMslhT

server.port=8084

##logging.level.org.hibernate.SQL=DEBUG
##logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

##spring.jpa.hibernate.ddl-auto=create
#spring.datasource.url=jdbc:postgresql://ownntendb.cpiw6y42k42b.ap-south-1.rds.amazonaws.com/ClubDB
#jpa.datasource.url=jdbc:postgresql://database-1.cyxua3xb4fm4.us-east-1.rds.amazonaws.com:5432/postgres                              
#spring.datasource.username=ownntenDB
#spring.datasource.password=Ownnten2021

spring.datasource.url=jdbc:postgresql://localhost:5432/Clubdb
jpa.datasource.url=jdbc:postgresql://database-1.cyxua3xb4fm4.us-east-1.rds.amazonaws.com:5432/postgres                                    
spring.datasource.username=postgres
spring.datasource.password=test
#spring.jpa.hibernate.ddl-auto=create
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.max-lifetime=1800

spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.datasource.test-while-idle=true
spring.datasource.validation-query=SELECT 1;
spring.datasource.time-between-eviction-runs-millis=60000
spring.datasource.remove-abandoned=true
spring.datasource.remove-abandoned-timeout=60

##spring.logstash.url= 192.168.99.100:5000

##Mail Config

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ownnten.contactus@gmail.com
spring.mail.password=xobinpwlubddgduf

##logging.level.org.springframework.web.filter.CommonsRequestLoggingFilter=DEBUG

# Other properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

# TLS , port 587
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.authentication=plain
#whatsapp.gateway=Curebay@123

spring.env.name=test


